CREATE TABLE IF NOT EXISTS STUDENT (
    ROLL_NO TEXT PRIMARY KEY,
    NAME TEXT NOT NULL,
    ADDRESS TEXT,
    PHONE TEXT,
    AGE INTEGER
);
INSERT INTO STUDENT (ROLL_NO, NAME, ADDRESS, PHONE, AGE) VALUES
('1', 'SAM', 'NEW YORK', '******', 18),
('2', 'JAMES', 'MICHIGAN', '******', 18),
('3', 'NATHAN', 'ORLANDO', '******', 20),
('4', 'ASH', 'NEW YORK', '******', 18),
('5', 'RAYMOND', 'ORLANDO', '******', 20),
('6', 'MARSH', 'MICHIGAN', '******', 18);

SELECT * FROM STUDENT;
SELECT * FROM STUDENT WHERE AGE = 18 AND ADDRESS = 'NEW YORK';
SELECT * FROM STUDENT WHERE AGE = 18 AND NAME = 'SAM';
SELECT * FROM STUDENT WHERE NAME = 'SAME' OR NAME = 'NATHAN';
SELECT * FROM STUDENT WHERE NAME = 18 OR AGE = 20;
SELECT * FROM STUDENT WHERE AGE = 18 AND (NAME = 'SAM' OR NAME = 'JAMES');